### ISSUE TITLE
Error with parse_junit comand

### ISSUE THREAD

**Issue by MichalMu** [gurock/trcli#137] opened 2023-03-30 10:43 UTC
I have a problem with trcli parse_junit. When I try to send test result I get Error: No such command 'parse_junit'.
I installed trcli using pip. Trcli command show:
TestRail CLI v1.4.3
Copyright 2021 Gurock Software GmbH - www.gurock.com
Supported and loaded modules:
    - parse_junit: JUnit XML Files (& Similar)
but when I try trcli parse_junit --help I also get the same error. I try to reinstall trcli, but it not help. I'm using python3.10.10 version. 
What could be the problem and how to solve it?

**Comment by nchua-msd** [comment] 2023-05-29 03:56
I'm having the same issue. I think it's trcli that's having an issue. I tried to uninstall and reinstall trcli, but now I am unable to install it.

**Comment by virdok** [comment] 2023-07-17 10:58
Still having the same issue. For some reason parse_junit command is not available and of course not displayed in the command line `trcli --help`

**Comment by VoorheesM** [comment] 2023-07-17 19:52
Hello, This bug is also affecting me, not sure what i can do for a work around

**Comment by pranit-kenjale** [comment] 2023-07-28 07:49
Look like there is still no work around. Command 'parse_junit' is not working for me with the below versions:

trcli==1.5.0
pyserde==0.12.1 or pyserde==0.11.1

**Comment by pranit-kenjale** [comment] 2023-07-29 01:57
@VoorheesM Can you plz share the versions that are working for you and the sequence of installation if it is relevant.

**Comment by VoorheesM** [comment] 2023-07-29 04:56
@pranit-kenjale sure,
run:  
pip install pyserde==0.11.1
pip install trcli==1.5.0

let me know if this fixes for you as well. Also this issue is a duplicate of https://github.com/gurock/trcli/issues/154

**Comment by pranit-kenjale** [comment] 2023-07-29 08:25
@VoorheesM Somehow it still did not help me.
But running [this](https://github.com/gurock/trcli/issues/137#issuecomment-1589134484) solution from `pip3 install --force-reinstall trcli` has finally helped me get past this problem.

**Closed** 2023-09-06 14:30 UTC
Labels: enhancement, priority-high
