### ISSUE TITLE
Overwrite the section-id that is provided within the import file

### ISSUE THREAD

**Issue by Testinator-X** [gurock/trcli#71] opened 2022-05-24 20:48 UTC
**Steps to reproduce:** 

* Import the following report:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Functional Tests Suite" time="150.939" tests="2" failures="0" errors="0">
   <testsuite name="Functional Tests Suite" tests="2" failures="0" errors="0" time="150.939" skipped="0" timestamp="2022-05-18 14:57:42" hostname="localhost - computername" id="Test Suites/Functional Tests Suite">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="C:\\Users\\myusername\\Katalon Studio\\Learning KS Web\\Reports\\20220518_145736\\Functional Tests Suite\\20220518_145737"/>
         <property name="logFiles" value="C:\\Users\\myusername\\Katalon Studio\\Learning KS Web\\Reports\\20220518_145736\\Functional Tests Suite\\20220518_145737\\execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="localhost - computername"/>
         <property name="os" value="Windows 10 64bit"/>
         <property name="katalonVersion" value="8.3.5.208"/>
         <property name="browser" value="Chrome 101.0.4951.67"/>
         <property name="hostAddress" value="127.0.0.1"/>
         <property name="sessionId" value="b48814780035cdbfdcb820cc6131f166"/>
         <property name="seleniumVersion" value="3.141.59"/>
         <property name="proxyInformation" value="ProxyInformation { proxyOption=NO_PROXY, proxyServerType=HTTP, username=, password=********, proxyServerAddress=, proxyServerPort=0, executionList=&quot;&quot;, isApplyToDesiredCapabilities=true }"/>
         <property name="platform" value="Windows 10"/>
      </properties>
      <testcase name="Test Cases/Add to Cart Test" time="73.239" classname="Test Cases/Add to Cart Test" status="PASSED">
         <system-out><![CDATA[2022-05-18 14:57:43 - [TEST_CASE][PASSED] - Test Cases/Add to Cart Test: Test Cases/Add to Cart Test

2022-05-18 14:57:43 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

2022-05-18 14:57:43 - [MESSAGE][INFO] - Starting 'Chrome' driver

2022-05-18 14:57:43 - [MESSAGE][INFO] - Action delay is set to 0 milliseconds

2022-05-18 14:57:54 - [MESSAGE][PASSED] - Browser is opened with url: ''

2022-05-18 14:57:54 - [TEST_STEP][PASSED] - navigateToUrl(WebsiteURL): Navigate to 'http://automationpractice.com' successfully

2022-05-18 14:58:16 - [MESSAGE][PASSED] - Navigate to 'http://automationpractice.com' successfully

2022-05-18 14:58:16 - [TEST_STEP][PASSED] - click(findTestObject("Object Repository/Home Page/a_Product 2")): Object: 'Object Repository/Home Page/a_Product 2' is clicked on

2022-05-18 14:58:28 - [MESSAGE][PASSED] - Object: 'Object Repository/Home Page/a_Product 2' is clicked on

2022-05-18 14:58:28 - [TEST_STEP][PASSED] - click(findTestObject("Object Repository/Product and Category Pages/Product Details Page/button_Add to cart")): Object: 'Object Repository/Product and Category Pages/Product Details Page/button_Add to cart' is clicked on

2022-05-18 14:58:28 - [MESSAGE][PASSED] - Object: 'Object Repository/Product and Category Pages/Product Details Page/button_Add to cart' is clicked on

2022-05-18 14:58:28 - [TEST_STEP][PASSED] - click(findTestObject("Object Repository/Product and Category Pages/Add to Cart Conrirmation Popup/button_Proceed to checkout")): Object: 'Object Repository/Product and Category Pages/Add to Cart Conrirmation Popup/button_Proceed to checkout' is clicked on

2022-05-18 14:58:52 - [MESSAGE][PASSED] - Object: 'Object Repository/Product and Category Pages/Add to Cart Conrirmation Popup/button_Proceed to checkout' is clicked on

2022-05-18 14:58:52 - [TEST_STEP][PASSED] - verifyElementText(findTestObject("Object Repository/Checkout Pages/Shopping Cart Summary Page/span_Number of products"), "1 Product"): Actual text and expected text of test object 'Object Repository/Checkout Pages/Shopping Cart Summary Page/span_Number of products' are matched.

2022-05-18 14:58:52 - [MESSAGE][PASSED] - Actual text and expected text of test object 'Object Repository/Checkout Pages/Shopping Cart Summary Page/span_Number of products' are matched.

2022-05-18 14:58:52 - [TEST_STEP][PASSED] - delay(3): Delayed 3 second(s)

2022-05-18 14:58:55 - [MESSAGE][PASSED] - Delayed 3 second(s)

2022-05-18 14:58:55 - [TEST_STEP][PASSED] - closeBrowser(): Browser is closed

2022-05-18 14:58:56 - [MESSAGE][PASSED] - Browser is closed]]></system-out>
         <system-err><![CDATA[]]></system-err>
      </testcase>
      <testcase name="Test Cases/User Account Tests/Login Tests/Login Manual Mode" time="77.47" classname="Test Cases/User Account Tests/Login Tests/Login Manual Mode" status="PASSED">
         <system-out><![CDATA[2022-05-18 14:58:56 - [TEST_CASE][PASSED] - Test Cases/User Account Tests/Login Tests/Login Manual Mode: Test Cases/User Account Tests/Login Tests/Login Manual Mode

2022-05-18 14:58:56 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

2022-05-18 14:58:56 - [MESSAGE][INFO] - Starting 'Chrome' driver

2022-05-18 14:58:56 - [MESSAGE][INFO] - Action delay is set to 0 milliseconds

2022-05-18 14:59:04 - [MESSAGE][PASSED] - Browser is opened with url: ''

2022-05-18 14:59:04 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

2022-05-18 14:59:04 - [MESSAGE][PASSED] - Current window maximized

2022-05-18 14:59:04 - [TEST_STEP][PASSED] - navigateToUrl(WebsiteURL): Navigate to 'http://automationpractice.com' successfully

2022-05-18 14:59:23 - [MESSAGE][PASSED] - Navigate to 'http://automationpractice.com' successfully

2022-05-18 14:59:23 - [TEST_STEP][PASSED] - click(findTestObject("Home Page/button_Sign in")): Object: 'Object Repository/Home Page/button_Sign in' is clicked on

2022-05-18 14:59:41 - [MESSAGE][PASSED] - Object: 'Object Repository/Home Page/button_Sign in' is clicked on

2022-05-18 14:59:41 - [TEST_STEP][PASSED] - setText(findTestObject("User Account Pages/Login Page/Login Section/input_Email address"), "jane.doe@example.com"): Text 'jane.doe@example.com' is set on object 'Object Repository/User Account Pages/Login Page/Login Section/input_Email address'

2022-05-18 14:59:42 - [MESSAGE][PASSED] - Text 'jane.doe@example.com' is set on object 'Object Repository/User Account Pages/Login Page/Login Section/input_Email address'

2022-05-18 14:59:42 - [TEST_STEP][PASSED] - setEncryptedText(findTestObject("User Account Pages/Login Page/Login Section/input_Password"), "2yzypAZhesWDBbg9RlLtEQ=="): Text ****** has been set on object 'Object Repository/User Account Pages/Login Page/Login Section/input_Password'

2022-05-18 14:59:43 - [MESSAGE][PASSED] - Text ****** has been set on object 'Object Repository/User Account Pages/Login Page/Login Section/input_Password'

2022-05-18 14:59:43 - [TEST_STEP][PASSED] - click(findTestObject("User Account Pages/Login Page/Login Section/button_Sign in")): Object: 'Object Repository/User Account Pages/Login Page/Login Section/button_Sign in' is clicked on

2022-05-18 14:59:53 - [MESSAGE][PASSED] - Object: 'Object Repository/User Account Pages/Login Page/Login Section/button_Sign in' is clicked on

2022-05-18 14:59:53 - [TEST_STEP][PASSED] - verifyElementVisible(findTestObject("User Account Pages/My Account Page/h1_My account")): Object 'Object Repository/User Account Pages/My Account Page/h1_My account' is visible

2022-05-18 15:00:13 - [MESSAGE][PASSED] - Object 'Object Repository/User Account Pages/My Account Page/h1_My account' is visible

2022-05-18 15:00:13 - [TEST_STEP][PASSED] - closeBrowser(): Browser is closed

2022-05-18 15:00:13 - [MESSAGE][PASSED] - Browser is closed]]></system-out>
         <system-err><![CDATA[]]></system-err>
      </testcase>
      <system-out><![CDATA[2022-05-18 14:57:42 - [TEST_SUITE][PASSED] - Functional Tests Suite: Test Cases/User Account Tests/Login Tests/Login Manual Mode]]></system-out>
      <system-err><![CDATA[]]></system-err>
   </testsuite>
</testsuites>
```

**Actual Result**
* I got the error: `ValueError: invalid literal for int() with base 10: 'Test Suites/Functional Tests Suite'`, even when I ran it with the commandline parameter `--suite-id 14`
* After some try and error, I manually edited this report and completely removed the ID id="Test Suites/Functional Tests Suite" from the report file, afterwards the report could be processed

**Expected Result**
* A command line parameter should overwrite the elements in the file.

**Comment by Testinator-X** [comment] 2022-07-03 18:58
@d-rede 

Thanks to the updated README, I have since found out that the id "Test Suites/Functional Tests Suite" that I removed does not seem to define the suite to import into, but instead defines the section within the suite. Is there a commandline parameter that can be used to overwrite in which section(s) it should be imported?

**Comment by Testinator-X** [comment] 2023-02-10 17:14
@d-rede please help

**Comment by d-rede** [comment] 2023-02-22 16:01
Hello @Testinator-X 

As originally designed, the CLI maps `testsuite` XML elements to TestRail sections and tries to match the `id` against the ID of a section in TestRail. This behavior does seem like something that may be undesirable, so I will analyze it and consider a potential fix.

**Comment by d-rede** [comment] 2023-02-22 18:07
@Testinator-X this was in fact undesired behavior and a fix was applied in `v1.4.3`. The `id` attributes are no longer being considered.

**Comment by Testinator-X** [comment] 2023-02-22 22:24
@d-rede I've updated to TestRail CLI v1.4.3 but I still can't import the .xml file I provided in the description. I'm still getting the error "`ValueError: invalid literal for int() with base 10: 'Test Suites/Functional Tests Suite'`" 

I still have to manually replace the ID in the line

   `<testsuite name="Functional Tests Suite" tests="2" failures="0" errors="0" time="150.939" skipped="0" timestamp="2022-05-18 14:57:42" hostname="localhost - computername" id="Test Suites/Functional Tests Suite">`

With an Section ID that exists in my project eg. 

`<testsuite name="Functional Tests Suite" tests="2" failures="0" errors="0" time="150.939" skipped="0" timestamp="2022-05-18 14:57:42" hostname="localhost - computername" id="9">`

How to overwrite the group ID via command line?
Btw. Is there an easy way to get the Section ID I want to import into via TestRail web frontend and not via API?

**Comment by d-rede** [comment] 2023-02-23 18:32
Hello @Testinator-X 

I see your issue is different from what I initially thought it was, thanks for re-surfacing it.

There are two separate points here though:
1. Currently the CLI expects all IDs in the report to be integers, but it isn't really using them, so I will provide a fix to fully ignore the IDs
2. You are requesting to specify the ID of sections (`<testsuite>` elements in the XML), but we currently don't have plans to support that. The sections are matched by name, so the CLI will look for a section with the same name as the `<testsuite>` element or it will create a new section. The `--suite-id` argument is for multisuite type projects, where you have to specify the suite you want your results in.

**Comment by d-rede** [comment] 2023-04-06 17:20
Hello again @Testinator-X 

Just letting you know that point number 1 on the last comment has been fixed. Also, since point number 2 is not a bug and it's not something we intend to support, I'm closing this bug.

Cheers

**Closed by d-rede** 2023-04-06 17:20 UTC
Labels: bug
