### ISSUE TITLE
Flag for Section parent ID to nest automated tests in to

### ISSUE THREAD

**Issue by BittahCriminal** [gurock/trcli#85] opened 2022-07-18 08:15 UTC
### What would you like the TestRail CLI to be able to do?

Been using the tool and there isn't a good way to organize the tests by means of the automation. It would be nice to specify a specific parent ID to target and nest test cases inside of.

### Why is this feature necessary on the TestRail CLI?

It would allow customization of where the tests go when using automation of the trcli

### Interested in implementing it yourself?

Maybe, let's talk!

**Comment by Testinator-X** [comment] 2023-02-10 17:17
seems to be a duplicate of https://github.com/gurock/trcli/issues/71

**Comment by Testinator-X** [comment] 2023-02-22 23:23
we're having a result file like this: [results.zip](https://github.com/gurock/trcli/files/10809076/results.zip)

which generates a TestCases as follows: 

![chrome_lLsXpB2rwT](https://user-images.githubusercontent.com/106194066/220785486-3c5bb2d3-26cf-4fce-ade4-d9d9f902abf7.png)

It would also be great to parse the name and create subsections from the testcase name or classname attribute as follows

```
|-_Test Cases_
    |- **Add to Cart Test**
    |-_User Account Tests_
        |-_Login Tests_
            |-**Login Manual Mode**
```

* _Italics = (Sub)Section Name_ 
* **Bold = TestCase Name**

**Closed** 2023-09-06 14:30 UTC
Labels: enhancement, priority-high
