### ISSUE TITLE
automation_id appears to be limited to 250 characters

### ISSUE THREAD

**Issue by andrewgbell** [gurock/trcli#92] opened 2022-08-05 11:51 UTC
### TestRail CLI Version

1.3.0

### CLI Environment

Windows 11 Pro, Mac m1

### TestRail Version

7.5.4

### TestRail Instance Type

Professional Cloud

### Current behavior

Trying to import with long test cases gives the error

Field :custom_automation_id is too long (250 characters at most)

### Desired behavior

the import should succeed regardless of automation_id length, as no limitation is mentioned in the documentation.

### More Details

I can't find anything in the documentation that mentions this limitation when creating the automation_id field as a string.  Is there any workaround to this, we have many test names which go over this limit so it would not be an easy task to reduce below.

When we try this with shorter test cases, the import works without problem.

A possible solution would be to change automation_id field to Text in place of String potentially, though it's not something we've tried, or whether this would be a workaround.

**Comment by shashankgumte** [comment] 2022-08-23 06:44
I have created automation_id as custom field in testrail and selected data type as **_text_** as workaround.

**Comment by andrewgbell** [comment] 2022-08-23 18:36
Didn't work for us, get the error:
Field :title is too long (250 characters at most).

When automation_id is a text field.

**Comment by shashankgumte** [comment] 2022-08-24 08:20
@andrewgbell This is working for us previously I was using string data type then converted to text data type . Now it is accepting more than 250 characters in automation_id custom field.

**Comment by ncbullock** [comment] 2022-09-21 20:28
@shashankgumte how were you able to "convert" from a string type to text type?  Once a custom field is defined, the system will not allow the type to be changed.  We also tried deleting the custom field so we could re-create with the text type, but can't find any way to delete a custom field.

**Comment by dominicwilliamslandmark** [comment] 2023-02-20 16:44
Had the same issue and got in touch with the TestRail support. They stated that this is by design and I'm welcome to use the API instead which has a limit of 4000 characters. They provided me the reasons why it was implemented with this limit and have also said they've raised a feature request.

1. Design decision: The CLI tool has been designed to have a smaller limit on certain fields to encourage users to provide concise and specific information. This can help to reduce clutter and make the tool more user-friendly.
2. Performance: The CLI tool limit the length of certain fields to ensure optimal performance. Larger fields usually take longer to process, which could impact the overall performance of the tool.
3. Compatibility: The CLI tool is designed to work with multiple versions of TestRail, and may have a limit on certain fields to ensure compatibility with older versions of TestRail.

**Comment by d-rede** [comment] 2023-09-04 15:46
Hello everyone,

Unfortunately, we didn't anticipate that using a `string type` field could cause such inconvenience due to size limitations. We will change our documentation and start suggesting that users opt for a `text type` field.

@ncbullock while it may not be ideal due to the loss of all field data associated to the field, TestRail does allow deleting and re-creating custom fields with the same ID. You can delete the field under **Administration > Customizations > Case Fields** by clicking the **red X icon**.

@andrewgbell `string type` fields also look like text, are you sure the field is configured as a `text type`?

**Comment by andrewgbell** [comment] 2023-09-04 16:03
> Hello everyone,
> 
> Unfortunately, we didn't anticipate that using a `string type` field could cause such inconvenience due to size limitations. We will change our documentation and start suggesting that users opt for a `text type` field.
> 
> @ncbullock while it may not be ideal due to the loss of all field data associated to the field, TestRail does allow deleting and re-creating custom fields with the same ID. You can delete the field under **Administration > Customizations > Case Fields** by clicking the **red X icon**.
> 
> @andrewgbell `string type` fields also look like text, are you sure the field is configured as a `text type`?

Yes.  Though due to limitations in the trcli we've ended up using ou own integration.

**Comment by bitcoder** [comment] 2023-10-26 16:38
We'll add a note on the TRCLI documentation to make the current behaviour clear and provide the  `text type` field suggestion

**Comment by AlexTRGit** [comment] 2024-02-27 09:54
I have the same issue as described above [Field :title is too long (250 characters at most)].
We are trying to Upload automated test results from JUnit reports.
From TestRail, we deleted the automation_id - type: string and re-created it with type: Text but we got the same error message.
Is there someone who resolved this issue and can advise how we can fix it?

**Comment by bitcoder** [comment] 2024-02-27 10:58
@AlexTRGit  did you recreated the "custom_automation_id" or the  "automation_id" field?

**Comment by AlexTRGit** [comment] 2024-02-27 11:15
> @AlexTRGit did you recreated the "custom_automation_id" or the "automation_id" field? it should be `automation_id`. As `text` it should not be limited to that size limit; can you please double check your configuration and see if that text field is applied to the project you're importing the results to?

Hey, yes I recreated the automation_id and set: Label:automation_id, SystemName:automation_id, Type:Text, Project:All Projects.

**Comment by bitcoder** [comment] 2024-02-27 11:30
@AlexTRGit , I just noticed that the problem is not with the `automation_id` field but with the `title` field..

**Comment by bitcoder** [comment] 2024-02-27 11:48
@AlexTRGit  I filled out a bug #207 ; it's really not expected to have very long titles on test cases but we need to think on a workaround that makes sense

**Comment by AlexTRGit** [comment] 2024-02-27 11:50
[report.txt](https://github.com/gurock/trcli/files/14418931/report.txt)
Hey, I have attached the report please check and advise.

**Comment by bitcoder** [comment] 2024-02-27 11:54
> [report.txt](https://github.com/gurock/trcli/files/14418931/report.txt) Hey, I have attached the report please check and advise.

thanks; let's please the move the discussion on the #207 issue. Can you share the JUnit XML report on that bug report, so I can analyze its content?

**Comment by bitcoder** [comment] 2024-03-05 11:21
I'll close this in the next days as:

- the `automation_id` has been explicitly mentioned to be set as text field in the documentation, so this problem doesnt occur anymore
- there was a unrelated issue being discussed here related to the `title` field.. which was been tracked on a separate issue #207, which has been addressed in v1.9.1 just released

**Closed** 2024-03-14 17:44 UTC
Labels: bug
